# Generated by Django 4.0.4 on 2022-05-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vactions', '0007_vaction_delete_vaction_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaction_info',
            fields=[
                ('emp_id', models.TextField(max_length=5, primary_key=True, serialize=False)),
                ('ft_name', models.TextField(max_length=20)),
                ('lt_name', models.TextField(max_length=20)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(max_length=50)),
                ('num_days', models.TextField()),
                ('reason', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Vaction',
        ),
    ]
