# Generated by Django 4.0.4 on 2022-05-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vactions', '0009_vaction_delete_vaction_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaction_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField(max_length=5, unique=True)),
                ('ft_name', models.TextField(max_length=20)),
                ('lt_name', models.TextField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_days', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(default='0', max_length=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Vaction',
        ),
    ]
