# Generated by Django 4.0.4 on 2022-05-22 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_rename_addmember_member'),
        ('HumanResources', '0002_employee_info_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='emp_info',
            fields=[
                ('employeeid', models.IntegerField(max_length=5, primary_key=True, serialize=False)),
                ('date_of_birth', models.DateField()),
                ('employee_Email', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=1)),
                ('Marital_Status', models.CharField(max_length=10, null=True)),
                ('Salary', models.IntegerField(max_length=8, null=True)),
                ('firstname', models.CharField(max_length=15)),
                ('lastname', models.CharField(max_length=15)),
                ('employee_phone', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=150, null=True)),
                ('memberid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sign.member')),
            ],
        ),
        migrations.DeleteModel(
            name='Employee_info',
        ),
    ]
