# Generated by Django 4.0.4 on 2022-05-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addmember',
            new_name='Member',
        ),
    ]
